title: 'nm,nmnmn'
description: 'mnmnmn,mnmnmnmnm,nm, n'
template:
  repo: nmnmnmn-template
  name: nmnmnmn
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: createStatus
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
